name: Convert XLSX to Parquet (High Compression)
on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.xlsx"   # ✅ 레포 내 모든 엑셀 감시

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pandas pyarrow openpyxl
      - name: Convert all .xlsx in repo (Parquet only)
        run: |
          python - << 'PY'
          import os, json, pandas as pd, pyarrow as pa, pyarrow.parquet as pq
          from pathlib import Path

          ROOT = Path(".")  # ✅ 전체 repo 탐색
          OUT = Path("converted")
          OUT.mkdir(exist_ok=True, parents=True)
          manifest = []

          for xlsx in ROOT.rglob("*.xlsx"):
              if ".github" in str(xlsx):
                  continue
              try:
                  book = pd.read_excel(xlsx, sheet_name=None, dtype=str)
                  for sname, df in book.items():
                      # 안전한 시트명 생성
                      safe = "".join(c if c.isalnum() or c in "-_." else "_" for c in sname)[:80]
                      base = OUT / f"{xlsx.stem}__{safe}"

                      # ✅ CSV 저장 제거
                      # df.to_csv(base.with_suffix(".csv"), index=False, encoding="utf-8-sig")

                      # ✅ Parquet만 저장 (Snappy 압축)
                      pq.write_table(
                          pa.Table.from_pandas(df),
                          base.with_suffix(".parquet"),
                          compression="snappy"
                      )

                      manifest.append({
                          "xlsx": str(xlsx),
                          "sheet": sname,
                          "parquet": str(base.with_suffix(".parquet"))
                      })
              except Exception as e:
                  print("⚠️ 변환 실패:", xlsx, e)

          (OUT / "manifest.json").write_text(
              json.dumps(manifest, ensure_ascii=False, indent=2),
              encoding="utf-8"
          )
          print("변환 완료:", len(manifest), "시트 변환됨 (Parquet only)")
          PY

      # ✅ 최고 압축률 (-9)
      - name: Zip outputs (high compression, Parquet only)
        run: |
          cd converted
          zip -9 -r ../converted_parquet_only.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: converted_parquet_only
          path: converted_parquet_only.zip
